name: 'Setup F´'
description: 'Setup the F´ repository and tools'
inputs:
  location:
    required: true
    default: $GITHUB_WORKSPACE
runs:
  using: "composite"
  steps:
  - run: git fetch --tags
    shell: bash
  - run: pip3 install setuptools_scm wheel urllib3
    shell: bash
  - run: pip3 install -r ${{ inputs.location }}/requirements.txt
    shell: bash
  - run: which fprime-util
    shell: bash
  - run: which fprime-gds
    shell: bash
  - run: which fpp-check
    shell: bash
    
